module.exports=function(grunt){
    
    grunt.initConfig({
        
        'gh-pages': {
            options: {
                base: 'dist' ,
                message: 'Generated by grunt gh-pages'
            } ,
            src: ['**/*']
        }
    });
    
    grunt.loadNpmTasks();
    
    
    grunt.registerTask("deploy",["gh-pages"]);
    
    
};